export function useMailInbox() {
  return [
    {
      id: "8483",
      user: "Nurul",
      email: "call.nurulid@gmail.com",
      avatar: "/images/nid.jpeg",
      time: "2024-04-03T15:45:00Z",
      title: "Completed tasks",
      desc: "Ulla sit amet rhoncus neque, non sodales libero. In mattis elementum erat, at molestie orci eleifend eu. Sed dignissim pulvinar du",
      isRead: false,
      isStarred: false,
      attachment: ["file.pdf", "pic.png"],
      label: ["meet", "bussiness"],
      company: "Lesliecompany",
      to: ["Alexandra Nowak", "Victor Mickiewicz"],
    },
    {
      id: "8322",
      user: "Annette Black",
      email: "black.annete@gmail.com",
      avatar: "",
      time: "2024-04-02T10:45:00Z",
      title: "Completed tasks",
      desc: "Ulla sit amet rhoncus neque, non sodales libero. In mattis elementum erat, at molestie orci eleifend eu. Sed dignissim pulvinar du",
      isRead: false,
      isStarred: true,
      attachment: [],
      label: ["team"],
      company: "Lesliecompany",
      to: ["Alexandra Nowak", "Victor Mickiewicz"],
    },
    {
      id: "6474",
      user: "Leslie Alexander",
      email: "leslie1209@gmail.com",
      avatar: "/images/christopher-campbell-rDEOVtE7vOs-unsplash.jpeg",
      time: "2024-03-13T04:15:00Z",
      title: "Completed tasks",
      desc: "Dear Alexandra, I hope this email finds you well. I am writing to inform you that we have scheduled a business meeting to discuss collaboration opportunities and the signing of the contract. We are excited to take this next step in our partnership. Please let us know if you have any specific topics or documents you would like to discuss during the meeting. Sincerely, Leslie Alexander",
      isRead: true,
      isStarred: false,
      attachment: ["file.pdf", "file.doc"],
      label: ["Meet", "Bussiness"],
      company: "Lesliecompany",
      to: ["Alexandra Nowak", "Victor Mickiewicz"],
    },
    {
      id: "5324",
      user: "Cody Fisher",
      email: "fffish.cody1@gmail.com",
      avatar: "/images/alexander-hipp-iEEBWgY_6lA-unsplash.jpg",
      time: "2024-03-03T12:24:00Z",
      title: "Completed tasks",
      desc: "Ulla sit amet rhoncus neque, non sodales libero. In mattis elementum erat, at molestie orci eleifend eu. Sed dignissim pulvinar du",
      isRead: false,
      isStarred: false,
      attachment: [],
      label: [],
      company: "Lesliecompany",
      to: ["Alexandra Nowak", "Victor Mickiewicz"],
    },
    {
      id: "9373",
      user: "Is.graphics",
      email: "Is.graphics@gmail.com",
      avatar: "/images/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpeg",
      time: "2024-01-03T16:32:00Z",
      title: "Completed tasks",
      desc: "Ulla sit amet rhoncus neque, non sodales libero. In mattis elementum erat, at molestie orci eleifend eu. Sed dignissim pulvinar du",
      isRead: true,
      isStarred: true,
      attachment: [],
      label: [],
      company: "Lesliecompany",
      to: ["Alexandra Nowak", "Victor Mickiewicz"],
    },
    {
      id: "5521",
      user: "Is.graphics",
      email: "Is.graphics@gmail.com",
      avatar: "/images/vicky-hladynets-C8Ta0gwPbQg-unsplash.jpeg",
      time: "2024-01-03T16:32:00Z",
      title: "Completed tasks",
      desc: "Ulla sit amet rhoncus neque, non sodales libero. In mattis elementum erat, at molestie orci eleifend eu. Sed dignissim pulvinar du",
      isRead: true,
      isStarred: true,
      attachment: [],
      label: [],
      company: "Lesliecompany",
      to: ["Alexandra Nowak", "Victor Mickiewicz"],
    },
  ];
} 
