import "./globals.css";

import type { Metadata } from "next";
import { Lexend } from "next/font/google";

import { DashboardLayout } from "./components/layout/DashboardLayout";
import { MessageDetailsProvider } from "./context/MessageDetailsContext";

const lexend = Lexend({
  weight: ["300"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <DashboardLayout>
          <MessageDetailsProvider>
            {children}
          </MessageDetailsProvider>
        </DashboardLayout>
      </body>
    </html>
  );
}
