import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Sidebar } from "./components/Sidebar";
import { SidebarProvider } from "./context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
        <main className="flex gap-8">
          <Sidebar />
          {children}
        </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
